### PR TITLE
Slack: Bugfix/Feature Addition - Fix Ask Question in Socket mode/Add AuthZ for Bot Commands

### PR DESCRIPTION
**Pull request by dallanwagz**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
While utilizing Slack 'Socket Mode', the 'ask question' action did not work. A fix has been added to remediate this. The 'ask question' action had a restriction where questions could only be sent via direct message. This restriction has been removed, and a new action parameter has been added to define which users are allowed to respond to the question. Access control has been added around the "Slack Bot" functionality. You can now specify what users are allowed to interact with Slack Bot, and which commands can be run.  

## What is the current behavior?
- The "ask question" action does not work while using Socket Mode
- The "ask question" action can only be sent directly to a single user (No channels/groups)
- SlackBot functionality is open to any user in the same channel as the Bot

## What is the new behavior?
- "ask question" action now works while using Socket Mode
- "ask question" action can now be sent to channels/groups, and you may specify which users are allowed to respond to the question via action parameters
- You can now specify which of the high level actions (list [containers/actions], run playbook, execute action, get container) can be executed by the SlackBot, and which users are allowed to interact with SlackBot.

## Other information
- When socket mode is enabled on a Slack App, interactivity between Slack and Splunk SOAR occurs over a WebSocket that is opened by Splunk SOAR during "on poll" cycles. There are numerous security benefits to this - 2 main benefits below

1. Splunk SOAR Rest Interface no longer needs to be exposed to the internet for Slack interactivity
2. Credentials for Splunk SOAR are no longer needed to be specified in URI inside of Slack App configuration

- To fix "ask question" for socket mode, I added a handler to catch responses to interactive messages (the question sent by ask question). The handler then puts the response into a json file and drops it into the app_states directly, where the 'ask question' action is monitoring on a loop, looking for the response to show up. (This is the same logic that was happening when the rest handler was receiving the response to the question)
- Permissions around SlackBot functionality were added to increase the overall security of the SOAR/Slack integration. We identified a gap where unexpected users could perform actions on Splunk SOAR just by solely being added to a channel that the SlackBot resides in

## Pay close attention to
- When performing any testing, please remember any changes to SlackBot asset config permissions require the bot the be restarted so that the bot can pick up the new state file.

### CODE REVIEW

**Comment by dallanwagz** [comment]
I have no visibility into why the AWS CodeBuild is failing. Can someone please provide me with the report?

**Comment by dallanwagz** [comment]
@mmomin-crest Can you please provide me information on the AWS CodeBuild test that is failing? I have no visibility into that so I can't do anything to remediate.

Also, in this commit: https://github.com/splunk-soar-connectors/slack/pull/18/commits/2ec02874192325ac953d5970aa7b58da50da39c6

I also noticed you removed "required": "True" from the following asset parameters
permit_bot_list
permit_bot_container
permit_bot_playbook
permit_bot_act

Can you please explain why? Those params have default values for False and are necessary for proper operation.

**Comment by mmomin-crest** [comment]
Hello @dallanwagz dallanwagz,
 There is a problem with the LGPL license of the websocket-client library we are using for socket connections in the AWS CodeBuild test. The websocket-client library has an LGPL license that is on the disapproved list, so we have requested our legal team for approval. Therefore, we are awaiting the legal team's response.  The 'required' parameter is redundant in the case of a boolean data type because if the user leaves it unchecked it will be considered false and in the case of a checked box, it will be true. To reduce this redundancy I removed the required attribute.

**Comment by mmomin-crest** [comment]
Hello @dallanwagz, 
The **websocket-client** library issue is resolved now and we are merging this branch into **hchavda-group-ask-question** branch and release both the changes in one process.

**Comment by dallanwagz** [comment]
Thanks @mmomin-crest. Where can I see the hchavda-group-ask-question branch?

**Comment by mmomin-crest** [comment]
Hello @dallanwagz, The hchavda-group-ask-question branch can be found here - https://github.com/splunk-soar-connectors/slack/tree/hchavda-group-ask-question

**Comment by dallanwagz** [comment]
@mmomin-crest Thank you for the link. I made some modifications to the existing “ask question” that allowed questions to be sent to groups and channels. Perhaps the new action “ask question channel” introduced in the hchavada is redundant, unless there is a compelling reason to have separate actions.

I see that static tests are now failing. Were there new checks added that caused this? Is it my responsibility to resolve these failures?

**Comment by mmomin-crest** [comment]
Hello @dallanwagz,
As per [above comment](https://github.com/splunk-soar-connectors/slack/pull/18#issuecomment-1305535057) we have another feature request that working same functionality as your changes and for same we merged your code changes to our branch and we have override certain parts of your code that are included in our [PR](https://github.com/splunk-soar-connectors/slack/pull/19).

**Pull request closed without merging**
