### PR TITLE
Slack: Bug fix/feature addition - Fix ordering bug in ask_question and add ability to lookup user by email address

### PR DESCRIPTION
**Pull request by dallanwagz**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [x] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [x] If this is a new connector or you are adding new actions
    - [x] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [x] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [x] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [x] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [x] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

- Fixed a bug where order of values passed in to "responses" on the "ask question" action were not maintained. This provided a poor user experience, especially in the case of "yes, no" inputs, as the order would often flip
- Fixed a bug where user ID's that start with "W" would fail in "get user" (See https://api.slack.com/changelog/2016-08-11-user-id-format-changes)
- Added the ability to lookup a user by their email address

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

- The ordering of values passed in to the "responses" parameter in "ask question" is not maintained
- "get user" lookup of User IDs that start with W always fail
- It is not possible to lookup a user by their email address

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

- Order of values passed in to the "responses" parameter in "ask question" action are maintained
- "get user" lookup for User IDs that start with W now succeed
- It is possible to lookup a user by their email address in addition to their unique ID

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Review by zamastyle — APPROVED** [review]
Changes look good to me. Slack unique IDs can start with W as well as U. Lookup user by email is a valuable addition. Ask question fix makes the slackbot update usable.

**Comment by achandya-crest** [comment]
Hello @dallanwagz, This is regarding email_address parameter in ask_question

1. In list_users action in the current app, we are getting email as **None** due to permissions mentioned in the app readme for this action. In order to get the email address for users listed in list_users action, we need to give user ‘user:read:email’ permission. This is because we are giving contains for the parameter email_address of get_user action. **This would help us use the output emails of list users in get user action's input.**


2. When adding an email address parameter as not required and changing the user_id to not required in get_user action, we would suggest you to **add a check in get_user action that either of user_id or email_address should be provided**. If none of them is given, the action should return proper error message.

Could you please look into this?

**Comment by dallanwagz** [comment]
@achandya-crest 

1. OK - Are you asking me to update the readme? If so, I can. 

2. OK - Will do today

**Comment by dallanwagz** [comment]
@achandya-crest Any update as to when this will be merged? Do you need anything from me?

**Comment by achandya-crest** [comment]
@dallanwagz We are validating the changes right now. I will keep you posted.

Also, we have to change min_phantom_version to 6.0.0 according to the developer best practices, is it fine for you?

**Comment by achandya-crest** [comment]
Hello @dallanwagz,
In the get user action, in case of an **invalid user_id and valid email_address** action will fail as it will consider just the user_id parameter and ignore email_address. Is it an expected scenario from your end?

**Comment by achandya-crest** [comment]
> @achandya-crest There isn't a valid use case to provide both email_address and user_id. It should be one or the other as they are both optional fields.

Ok then we will let it be as it is. Thanks.

**Review by mmomin-crest — APPROVED** [review]

**Review by dhwanis-crest — APPROVED** [review]

**Review by tonyc-phantom — APPROVED** [review]

**Review by splunk-jessica — APPROVED** [review]

**Pull request merged**
